### PR TITLE
Feat/migrate to cft

### LINKED ISSUE #4: Migrate to Standalone Chrome Driver and Chrome for Testing
As is recommended by [ChromeDriver](https://chromedriver.chromium.org/downloads), and since [Chrome for Testing](https://googlechromelabs.github.io/chrome-for-testing/) [has been announced](https://developer.chrome.com/blog/chrome-for-testing/), it is a better practice to use standalone chrome-headless-shell and chromedriver for convenience and compatibility. 

Currently, when an authentication is needed and the chromedriver mismatches the version of installed chrome, an auto update of the chromedriver will be triggered. However, this update won't be completed if there is no internet connection. Migrating to standalone chrome driver and chrome for testing can prevent this. Besides, current methods of managing chrome driver  (manual / auto update) are certainly going to expire over time.

### PR DESCRIPTION
**Pull request by yao-yun**
fix #4, migrate to chrome for testing and add basic cli support

### CODE REVIEW

**Comment by yao-yun** [comment]
doc update wip, will edit this pr when finished

**Comment by coolmoon327** [comment]
Thanks for your contribution, and I will check it today.

**Comment by yao-yun** [comment]
P.S. Chrome for testing and Chromedriver binaries were not included for [specific reasons](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github). These binaries are approximately 200 MB for a single platform and roughly 1 GB for all the supported platforms. You might want to consider using Git LFS to track a particular version of CFT and chromedriver, so that this project can run out-of-the-box.

**Comment by coolmoon327** [comment]
Firstly, thanks for your advice. However, there still exist some issues:

1. The 'match' syntax in 'setup_cft.py' requires at least Python 3.10, so you should announce the new environment requirements in the doc.
2. Your modified docker file has the same problem as above since you didn't specify the Python version while executing `apt-get install python3`.
3. It is unnecessary to push the driver files. I don't think students at UESTC cannot find a proper way to prepare their net env. And we can build and upload the docker version to DockerHub for those as lazy as me.

By the way, are you at the Qingshuihe campus these days? I'm a postgraduate of your school's vice dean 徐世中 and I'm gonna leave in the next few months (so I won't have the ability to test the project anymore). Maybe we can have a meal together offline and I want to set you as the collaborator if you have enough time to maintain this project.

If you are interested, plz contact me with my email shenyuhang327@gmail.com, and I will send my QQ number via it.

**Pull request merged**
